Мурзин С.А, "Английские шашки", 3530901/10004
Saloed/softdev-2022-spring-task-3 pull request #4
Opened 2022-05-18 15:00 UTC by SmurZik

2022-05-18 16:14 UTC, Saloed requested changes

2022-05-18 16:14 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +var turn = mutableListOf("black")
Глобальные константы -- норм. Глобальное что угодно другое -- не норм.

2022-05-18 16:14 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +fun update(oldCordX: Double, oldCordY: Double, x: Double, y:Double, queen: Boolean, white: String, cord:String) {
Передавать координаты как в интерфейсе и тут их как-то преобразовывать в координаты на доске -- не норм. Из-за необходимости такого преобразования, в логику приложения протекает кусок интерфейсной части.

2022-05-18 16:14 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +fun eatForQueen(oldPosX: Double, oldPosY: Double, posX: Double, posY: Double, loc: List<String>, white: String): Pair<String, String> {
Постарайтесь сократить дублирование кода

2022-05-18 22:21 UTC, SmurZik commented on src/main/kotlin/Logic.kt
> +fun update(oldCordX: Double, oldCordY: Double, x: Double, y:Double, queen: Boolean, white: String, cord:String) {
Не совсем понял, то есть в логику уже передавать координаты доски?

2022-05-19 08:06 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +fun update(oldCordX: Double, oldCordY: Double, x: Double, y:Double, queen: Boolean, white: String, cord:String) {
Ага

2022-05-19 08:08 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +            if (turnWhite[1] == "white") turnWhite.add("black")
И для того и для другого лучше использовать не строки, а enum

2022-05-19 17:35 UTC, SmurZik commented on src/main/kotlin/Logic.kt
> +            if (turnWhite[1] == "white") turnWhite.add("black")
Насколько я понял, в enum нельзя будет добавлять элемент или же удалять, тогда как мне тут это нужно

2022-05-24 08:27 UTC, Saloed requested changes

2022-05-24 08:27 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +    val ind = location.value.indexOf(oldCord)
`indexOf` это не самая лучшая операция. Судя по тому, что вам приходится делать, список это не лчшая структура данных для вашей задачи.

2022-05-24 08:27 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +    val oldX = listOfLetters1.indexOf(Letters.valueOf(oldCord.toString()[0].toString()))
Постарайтесь избавиться от такие цепочек преобразований вида `valueOf(toString)`

2022-05-24 08:27 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +    (white == Turn.White && y.toString()[1] == '8') || (white == Turn.Black && y.toString()[1] == '1')
Раз уж вы все координаты сделали `enum`, то вот такое сравнение со строками выглядит странно.

2022-05-24 08:27 UTC, Saloed commented on src/main/kotlin/Logic.kt
> +enum class Letters {
Я не совсем понял, зачем вы сделали `enum` всё, помимо `Turn`

2022-05-24 08:27 UTC, Saloed commented on src/main/kotlin/view.kt
> +val turnWhite = mutableStateOf(turn)
Глобальные изменяемые объекты это не норм

2022-06-02 16:21 UTC, closed without merging